name: Update README

on:
  schedule:
    - cron: "0 */6 * * *" # Ejecuta cada 6 horas
  workflow_dispatch: # Permite ejecución manual

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: ":zap: Actualizando actividad reciente en README"
          EMPTY_COMMIT_MSG: ":memo: Sin actividad reciente en los últimos eventos"
